### PR TITLE
Money question type

### PR DESCRIPTION
**Pull request by robmckinnon**
- Adds money question type.
- Required for possible MOJ fee remission smartanswers - see issue #128
- Added specs for money question and money answer.
- Refactored salary answer to make use of to_s() and humanize() logic in money answer.
- Also ran successfully smart-answers repo tests against this version of smartdown.
- Removed need to add new question types to long if/else statements in previous_question.rb and question_page.rb.
- New `Smartdown::Model::Element::Question.create_question_answer()` method instantiates correct question/answer instances.

### CODE REVIEW

**Comment by robmckinnon** [comment]
Adding some further specs. Not yet committed.

**Comment by dsingleton** [comment]
Hi Rob,

The overall change looks great, especially the refactoring on top of the Money question itself, much appreciated. The implementation is also :+1:, but there are a couple of v small changes that I think are worth making:

- Could you add some testing around `lib/smartdown/model/element/question.rb`? It's an improvement on the big ol' switch statement, but is a little less intuitive/readable, and a spec will help illustrate it and prevent regressions.
- Smartdown (generally) uses bracketed arguments for methods defs, could you do the same for any new methods? (eg, on [Question](https://github.com/ministryofjustice/smartdown/blob/money-question/lib/smartdown/model/element/question.rb)). 

Sorry those are picky points, but as Smartdown is becoming more mature, and getting outside contributions, its worth enforcing things more strictly.

I'm going to write up some of this in a `CONTRIBUTIONS` guide, so its more obviously documented for future contributors :)

With those changes in i'd be more than happy to merge this, it's a great contribution :+1:

**Comment by robmckinnon** [comment]
Further spec work now completed.

**Comment by robmckinnon** [comment]
Hi David,

Thanks for the feedback. I've made your recommended improvements. I added a spec for `lib/smartdown/model/element/question.rb` that explicitly tests question and answer get instantiated as expected. Agree the meta programming is little less intuitive/readable. Existing tests here and in the `smart-answers` repo implicity exercise the new implementation.

I've left the CHANGELOG version as '0.xx.x' - please edit before you release.

After the merge and release of `smartdown`, you can make money questions available in smart-answers with this PR: alphagov/smart-answers#1408

Hope this proves useful for other smart-answers!

**Comment by dsingleton** [comment]
Looks good to me. Thanks for making those changes :+1: 

Our release process for gems is to update the `CHANGELOG` and `version.rb` separately on a PR, so the changelog will updated then. I'll do that shortly.

**Pull request merged**
